### ISSUE TITLE
fit_transform method doesn't handle NaN

### ISSUE THREAD

**Issue by aaghamohammadi** [hamelsmu/ktext#15]
I have noticed that `fit_transform(train_df_raw)` raises an exception if the _train_df_raw_ contains _NaN_.
I simply handled it by invoking  `train_df.dropna(inplace=True)` before this method. However, it would be great if the method handles them by itself.

**Comment by hamelsmu** [comment]
Pull requests are welcome!

**Comment by hamelsmu** [comment]
Closing this issue for now, yes the library doesn't handle NaN but feel free to submit a PR with this change.  Thanks
