### ISSUE TITLE
OSError: Can't find model 'en'

### ISSUE THREAD

**Issue by rish-16** [hamelsmu/ktext#2]
Hello there!

I read your article on Medium and was really interested in working on your project. However, when I run the code as is, it gives me the error that the 'English' model is not available under spaCy. I have tried countless times to mitigate the error, but have found no way to get out of the situation.

Can I know what steps I can take to continue?

System info:
**platform**: macOS High Sierra vrs. 10.13.2
**graphics**: Intel Iris Graphics 6100 1536 MB
**memory**: 8 GB 1867 MHz DDR3

Cheers!

**Comment by rish-16** [comment]
Nevermind. I followed the SpaCy installation guide on their website. It's finally working!

**Comment by hamelsmu** [comment]
@rish-16 post your solution here!  I believe you had to run

```
python -m spacy download en
```
correct?

**Comment by rish-16** [comment]
Yah @hamelsmu That is the solution. I installed spaCy using a condo environment. Then I ran the program. It started the vectorising process.

**Comment by hamelsmu** [comment]
@rish-16 I updated this package to eliminate the `spacy` dependency.  You should also notice a significant speedup.  You can upgrade by 

```pip install -U ktext```
