### ISSUE TITLE
OSError: [Errno 12] Cannot allocate memory being thrown from apply_parallel

### ISSUE THREAD

**Issue by johnhaley81** [hamelsmu/ktext#3]
Hi hamelsmu! Thanks for this fantastic package. While I was going through your [blog post](https://towardsdatascience.com/how-to-create-data-products-that-are-magical-using-sequence-to-sequence-models-703f86a231f8) I was running into some issues with preprocessing the data. 

After some investigation I narrowed it down to tieing the concurrency of the parallelism to the number of cores of the machine [here](https://github.com/hamelsmu/ktext/blob/master/ktext/preprocess.py#L76).

I have a 32-core machine with 64GB of ram and due to the large overhead of each python thread my machine with start throwing `OSError`s while trying to execute `fit` in parallel. Turning down the number of threads to say, 20, fixes the problem.

I was trying to get a PR together but I wasn't super happy with any of the solutions I had. 

In the first solution I tried to get some exception handling in there that would scale down `cpu_cores` if the machine doesn't have enough memory to use all of them. However the parent process wasn't able to catch the exception it seems and the whole thing just dies. I'm not sure if I was missing anything. Here's my (unfinished) code for that:

```python
def apply_parallel(data: List[Any], func: Callable) -> List[Any]:
    """
    Apply function to list of elements.

    Automatically determines the chunk size.
    """
    cpu_cores = cpu_count()

    done = False

    while not done:
        try:
            chunk_size = ceil(len(data) / cpu_cores)
            pool = Pool(cpu_cores)
            transformed_data = pool.map(func, chunked(data, chunk_size), chunks$
            done = True
        except OSError:
            cpu_cores = cpu_cores - 2
        finally:
            pool.close()
            pool.join()

    return transformed_data
```

I'm not sure if I'm just missing something...

The other idea I had was to add a parameter to set a `max_num_threads` but that is also kind of lame, forcing the user to know ahead of time what their system can handle.

Another idea was to try and calculate the system's resources and the data to process and then set the limit in the method. That seems pretty brittle though.

Any ideas that you can add? Or am I missing something with catching the exception?

**Comment by johnhaley81** [comment]
Adding another thing, so I thought setting `cpu_count` to 20 fixes the problem but it just allows it to move onto the `build_corpus` step which it then dies on. Setting it to `cpu_count = 8` (which was what you were running on AWS fixes the problem and now I can parse 2E6 github issues on my machine.

**Comment by hamelsmu** [comment]
@johnhaley81 ok, I think the solution to this is to allow the user to set the number of threads instead of using all available threads.  Adding a method that sets the number of threads should work.  Thoughts?  

I'll be happy to review your PR if you are so inclined or I'm also happy to make the change sometime within the next couple of weeks (tag me if I forget!)

**Comment by johnhaley81** [comment]
Sounds good, I'll try and get something going.

**Comment by hamelsmu** [comment]
@johnhaley81 there is a new method called `set_num_processes`.  

Also you should observe a considerable speedup now.  Let me know how it goes.
