### ISSUE TITLE
Error in import "from ktext.preprocess import processor"

### ISSUE THREAD

**Issue by TobiasEl** [hamelsmu/ktext#9]
Hi.
I've download the ktext library, but when I run the program I have this error:

Traceback (most recent call last):
  File "as.py", line 16, in <module>
    from ktext.preprocess import processor
  File "/home/tobias/.local/lib/python2.7/site-packages/ktext/preprocess.py", line 35
    def count_len(tkn_doc: List[str]) -> List[int]:
                         ^
SyntaxError: invalid syntax

How can I solve this? I f you need to know I use this command "pip install ktext --user" to download.
Thanks.

**Comment by hamelsmu** [comment]
@TobiasEl can you please try this again?  Also this is only tested with `python 3`, can you try installing this with that instead?
